@baseUrl = http://localhost:3000
# Categories
# @name getAllCategories
GET {{baseUrl}}/categories
###
# @name addNewCategory
POST {{baseUrl}}/categories
Content-Type: application/json

{"name":"laptop"}
###
# @name updateCategory
PATCH  {{baseUrl}}/categories
###
# @name removeCategory
DELETE {{baseUrl}}/categories

